### ISSUE TITLE
NoMethodError: undefined method `property' for nil:NilClass

### ISSUE THREAD

**Issue by anke1460** [rgeo/activerecord-postgis-adapter#195]
It doesn't working when i set the point data to location column.
````
c = User.new(name: 'test')
c.location='POINT(-122 47)'
````
 It raise errors as follows.
````
NoMethodError: undefined method `property' for nil:NilClass
from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/rgeo-0.4.0/lib/rgeo/wkrep/wkt_parser.rb:168:in `_ensure_factory'
	from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/rgeo-0.4.0/lib/rgeo/wkrep/wkt_parser.rb:254:in `_parse_coords'
	from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/rgeo-0.4.0/lib/rgeo/wkrep/wkt_parser.rb:285:in `_parse_point'
	from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/rgeo-0.4.0/lib/rgeo/wkrep/wkt_parser.rb:214:in `_parse_type_tag'
	from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/rgeo-0.4.0/lib/rgeo/wkrep/wkt_parser.rb:144:in `parse'
	from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis/oid/spatial.rb:102:in `parse_wkt'
	from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis/oid/spatial.rb:90:in `type_cast'
	from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/type/value.rb:34:in `type_cast_from_user'
	from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/attribute.rb:110:in `type_cast'
	from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/attribute.rb:42:in `original_value'
	from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/attribute.rb:37:in `value'
	from /home/deploy/apps/projects/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/attribute.rb:50:in `changed_from?'

````

**Comment by stellard** [comment]
I had the same issue. I used the example configuration which did not work for my configuration since I was not using Geos. 

Mine looks like this and is working

```ruby
RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config|
  config.default = RGeo::Geographic.spherical_factory(srid: 4326)
end
```

**Comment by teeparham** [comment]
I updated the README to clarify the `SpatialFactoryStore` setup: https://github.com/rgeo/activerecord-postgis-adapter#configuring-activerecord . Hopefully this helps.

**Comment by bifork** [comment]
This issue is not resolved. Per your configuration at https://github.com/rgeo/activerecord-postgis-adapter#configuring-activerecord , the NoMethodError: undefined method `property' for nil:NilClass error still pops up.

**Comment by lukeipanda** [comment]
```
require 'rgeo-activerecord'

RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config|
  # By default, use the GEOS implementation for spatial columns.
  config.default = RGeo::Geos.factory_generator

  # But use a geographic implementation for point columns.
  config.register(RGeo::Geographic.spherical_factory(srid: 4326), geo_type: "point")
end
```
This error doesn't happen on localhost. But when deployed to heroku, it pops up.
——— Logs ———
```
heroku[router]: at=info method=POST path="/api/locations.json" host=ngrails-unfold.herokuapp.com request_id=4053b701-9d3e-479c-8a33-c44e539ccdc8 fwd="45.63.35.55" dyno=web.1 connect=3ms service=28ms status=500 bytes=551

Started POST "/api/locations.json" for 45.63.35.55 at 2016-11-15 14:36:41 +0000

Processing by LocationsController#create as JSON

Parameters: {"location"=>{"name"=>"San Francisco Airport", "latlon"=>"POINT(-122.381827 37.62161)"}}

BEGIN

Location Exists (1.7ms)  SELECT  1 AS one FROM "locations" WHERE "locations"."name" = $1 LIMIT $2  [["name", "San Francisco Airport"], ["LIMIT", 1]]
```
——— Error logs from heroku ———
```
ROLLBACK

Completed 500 Internal Server Error in 15ms (ActiveRecord: 6.1ms)

NoMethodError (undefined method `property' for nil:NilClass):

app/controllers/locations_controller.rb:20:in `create'
```
——— Success logs from localhost ———-
```
INSERT INTO "locations" ("name", "latlon", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["name", "San Francisco Airport"], ["latlon", "0020000001000010e6c05e986fda836eb54042cf90ea9e6eeb"], ["created_at", 2016-11-15 14:35:29 UTC], ["updated_at", 2016-11-15 14:35:29 UTC]]

COMMIT
```
What could be the cause of this error?

**Comment by bifork** [comment]
```
require 'rgeo-activerecord'

RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config|
  # By default, use the GEOS implementation for spatial columns.
  config.default = RGeo::Geos.factory_generator

  # But use a geographic implementation for point columns.
  config.register(RGeo::Geographic.spherical_factory(srid: 4326), geo_type: "point")
end
```
This error doesn't happen on localhost. But when deployed to heroku, it pops up.
——— Logs ———
```
heroku[router]: at=info method=POST path="/api/locations.json" host=ngrails-unfold.herokuapp.com request_id=4053b701-9d3e-479c-8a33-c44e539ccdc8 fwd="45.63.35.55" dyno=web.1 connect=3ms service=28ms status=500 bytes=551

Started POST "/api/locations.json" for 45.63.35.55 at 2016-11-15 14:36:41 +0000

Processing by LocationsController#create as JSON

Parameters: {"location"=>{"name"=>"San Francisco Airport", "latlon"=>"POINT(-122.381827 37.62161)"}}

BEGIN

Location Exists (1.7ms)  SELECT  1 AS one FROM "locations" WHERE "locations"."name" = $1 LIMIT $2  [["name", "San Francisco Airport"], ["LIMIT", 1]]
```
——— Error logs from heroku ———
```
ROLLBACK

Completed 500 Internal Server Error in 15ms (ActiveRecord: 6.1ms)

NoMethodError (undefined method `property' for nil:NilClass):

app/controllers/locations_controller.rb:20:in `create'
```
——— Success logs from localhost ———-
```
INSERT INTO "locations" ("name", "latlon", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["name", "San Francisco Airport"], ["latlon", "0020000001000010e6c05e986fda836eb54042cf90ea9e6eeb"], ["created_at", 2016-11-15 14:35:29 UTC], ["updated_at", 2016-11-15 14:35:29 UTC]]

COMMIT
```
What could be the cause of this error?

**Comment by teeparham** [comment]
Not enough information. Post a call stack, or better, sample code to re-create the problem.

**Comment by bifork** [comment]
This is the database settings of my project:
```
default: &default
  adapter: postgis
  encoding: unicode
  username: unfold_u
  password: password
  su_username: unfold_su
  su_password: Pa55w0rd
  schema_search_path: "public, postgis"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: unfold_development
  script_dir: /usr/local/opt/postgis/share/postgis
test:
  <<: *default
  database: unfold_test
  script_dir: /usr/local/opt/postgis/share/postgis

production:
  <<: *default
  database: unfold_production
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
  username: unfold
  password: <%= ENV['UNFOLD_DATABASE_PASSWORD'] %>
```

This is the way I enabled postgis on heroku:
```
$ heroku pg:psql --app ngrails-unfold
> CREATE EXTENSION postgis;
> select postgis_version();
            postgis_version            
---------------------------------------
 2.3 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)
```

This is the Location migration:
```
class CreateLocations < ActiveRecord::Migration[5.0]
  def change
    create_table :locations do |t|
      t.string :name, null: false
      t.st_point :latlon, geographic: true, null: false

      t.timestamps
    end

    add_index :locations, :name
  end
end
```

The full repository is here: https://github.com/bifork/ngrails-unfold 
The project was set up by following http://daniel-azuma.com/articles/georails/part-2 .
Deployed using these build packs:
1. https://github.com/cyberdelia/heroku-geo-buildpack.git
2. https://github.com/jasonswett/heroku-buildpack-nodejs
3. heroku/ruby

**Comment by bifork** [comment]
If you deployed an postgis adapter app to heroku, could you kindly add the walk-through to the README?

**Comment by teeparham** [comment]
It looks like you have things set up correctly to me. I don't have time to debug this now. You might have better luck getting help on Stack Overflow.

Yes - please open a new issue to improve Heroku setup information.

**Comment by bifork** [comment]
Thanks for your help.
I posted a question to http://stackoverflow.com/questions/40661658/how-to-set-up-a-postgis-adaptered-ruby-on-rails-app-for-heroku-deployment .
Created a new issue https://github.com/rgeo/activerecord-postgis-adapter/issues/240 

For now, I'd drop postgis for my app first, using a string for coordinates first. Currently I only need the coordinates to present an embedded map. Not sure if there is a good way to do geo-spatial calculations based on coordinates, without sending the logic to the database.

**Comment by asergiop21** [comment]
HI, @bifork a consult could solve the problem ?, I am having the same problem and I do not know how to solve it !.

regards

**Comment by bifork** [comment]
No luck. I quit postgis and used a string column instead (since I only intended to show a mark on a map). Ruby solutions are easy to break. Try other technologies if you really need to compute location data. Try more portable database solutions also.

**Comment by asergiop21** [comment]
Hi bifork, thank you very much for responding, after insisting on the
versions of rgeo, I could make it work, if it works, occupy version rails
5, ruby 2.3 and rgeo 0.60. With that I worked.

Greetings!

2017-03-16 0:01 GMT-03:00 bifork <notifications@github.com>:

**Comment by bifork** [comment]
Did you successfully deployed to Heroku, or just it works locally? I had no problem locally. But on Heroku it's broken.

**Comment by asergiop21** [comment]
I did Deploy on Digital Ocean! With success !, if I can help you in any way
let me know.
regards

2017-03-18 23:00 GMT-03:00 bifork <notifications@github.com>:

**Comment by Soliah** [comment]
So for those finding this issue via Google, I got this working by making sure the system packages required by the rgeo gem were installed on my system (in this case, within a Docker container).

Specifically `libproj-dev` and `libgeos-dev` on Ubuntu. Once these were installed and I reinstalled rgeo (which has native extensions that are linked against those 2 libraries) this error stopped occurring.

**Comment by archfish** [comment]
it call by rgeo CAPI, you should install both libgeos-dev and libproj-dev in debian. Here is my step:

```shell
cd /usr/local/bundle/gems/rgeo-0.6.0
ldd ext/geos_c_impl/geos_c_impl.so
ldd ext/proj4_c_impl/proj4_c_impl.so
```

output:

```log
## ldd ext/geos_c_impl/geos_c_impl.so
	linux-vdso.so.1 (0x00007ffed93cd000)
	libruby.so.2.3 => /usr/local/lib/libruby.so.2.3 (0x00007f6e16df5000)
	libgeos_c.so.1 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6e16bd8000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f6e16955000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6e16751000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f6e16519000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6e16215000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6e15e76000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6e174f2000)

## ldd ext/proj4_c_impl/proj4_c_impl.so
	linux-vdso.so.1 (0x00007ffed392f000)
	libruby.so.2.3 => /usr/local/lib/libruby.so.2.3 (0x00007f68e343f000)
	libproj.so.12 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f68e3222000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f68e2f9f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f68e2d9b000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f68e2b63000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f68e285f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f68e24c0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f68e3b30000)
```

maybe you get none *.so in that dir, you also need to install libgeos-dev and libproj-dev let it generate righ Makefile.

ENV:
OS: Debian GNU/Linux 9 (stretch)
RUBY: 2.3.8 with Rails 4.2.11.1
VERSION: activerecord-postgis-adapter (3.1.5)

GOOD LUCK!
